---
title: "市場リスク評価"
author: "Naoya Hieda"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
    number_sections: yes
    css: "/Users/naoya/Desktop/ToS/toc.css"
    toc_depth: 2
    pandoc_args: [
        "--from", "markdown+autolink_bare_uris+tex_math_single_backslash-implicit_figures"
        ]
---


```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.width=12,
               fig.height=9)
opts_knit$set(width=75)
set.seed(2017)
```


```{r package}
#実験で使う関数
source("/Users/naoya/Desktop/ToS/script/functions.R")
objects()
#パッケージのインストールと読み込み
#持ってないパッケージはインストールする
targetPackages <- c('zoo', 'xts','Quandl',
                    'quantmod','ggplot2','grid','reshape2','scales',
                    'dplyr','moments','xtable','gridExtra','snow','parallel') 
newPackages <- targetPackages[!(targetPackages %in% installed.packages()[,"Package"])]
if(length(newPackages)) install.packages(newPackages, repos = "http://cran.us.r-project.org")
for(package in targetPackages) library(package, character.only = T)
```

# 株価収益率の分析

```{r n225}
#データの読み込み
n225 <- read.csv("/Users/naoya/Desktop/ToS/data/nikkei225.csv",skip=1)
y <- NULL
#終値(1日の最後の値段)を使う
y$Close <- n225$PX_LAST
#日付データをDate型に変換
y$ymd <- as.POSIXct(n225$Date)
#データフレームにする(行列の列に名前がついているもの)
#ggplotはdata.frameのデータにしか使えないので注意
df <-data.frame(dt=y$ymd, x=y$Close)
```

## 日経225<br>平均株価指数の遷移

```{r fig1}
#ggplotで日経平均株価をplot
#ggplotの各関数の意味は自分で調べること
ggplot(df,aes(x=dt,y=x))+geom_line()+
        scale_x_datetime(breaks = date_breaks("6 months"))+
        labs(y="N225")+
        theme_bw()+
  theme(axis.title.x = element_text(size=25),axis.title.y = element_text(size=25))+
  theme(axis.text.x = element_text(size=25),axis.text.y = element_text(size=25)) +
  theme(legend.title = element_text(size=15),legend.text = element_text(size=15))
```

## 日経平均の<br>対数収益率の推移

```{r fig2}
#日経平均の対数収益率をplot
df$log_x <- c(NA,diff(log(df$x))*100)
ggplot(df[-1,],aes(dt,log_x))+geom_line()+
        scale_x_datetime(breaks = date_breaks("6 months"))+
        labs(y="log return")+
        theme_bw()+
        theme(strip.background = element_blank(),
              panel.border = element_rect(colour = "black"))+
  theme(axis.title.x = element_text(size=25),axis.title.y = element_text(size=25))+
  theme(axis.text.x = element_text(size=25),axis.text.y = element_text(size=25)) +
  theme(legend.title = element_text(size=15),legend.text = element_text(size=15))
```

# 最尤推定

## 尺度変換した<br>sinh-arcsinh分布の<br>パラメータ推定

```{r MLE}
rt <- df$log_x[-1]
rt <- rt[rt!=0]
fit <- mle.dfas2(rt, ini=c(0, log(0.2), -0.2, 0.5))

fit$par2

df= data.frame(log_return=rt)
ggplot(df, aes(log_return))+
        geom_histogram(binwidth=.3, colour="black", fill="white",
                          aes(y=..density..))+
      #scale_fill_gradient("Count", low="#DCDCDC", high="#7C7C7C")+
       xlim(min(rt),max(rt))+
       stat_function(fun=dnorm,
                         #colour="violetred",
                         aes(colour ="Normal distribution"),
                         size=1,
                         n=401,
                         args=list(mean=mean(rt), sd = sd(rt)))+
       stat_function(fun=dfas2,
                         #colour="green",
                         aes(colour ="Tos sinh-arcsinh distribution"),
                         size=1,
                         n=401,
                         args=list(mu=fit$par2[1],
                                  sigma = fit$par2[2],
                                  lambda = fit$par2[3],
                                  delta = fit$par2[4]))+
        theme_bw()+
  theme(legend.position = "bottom")+
  theme(axis.title.x = element_text(size=25),axis.title.y = element_text(size=25))+
  theme(axis.text.x = element_text(size=25),axis.text.y = element_text(size=25)) +
  theme(legend.title = element_text(size=25),legend.text = element_text(size=25))
```


## モーメントの計算

```{r moments}
# パラメータが与えられた時のFA分布について
out.mom <- fas2.moment(fit$par2)
# 表にする
hyou.a <- matrix(0, 3,4)
hyou.a[1,] <- c( mean(rt), sd(rt), skewness(rt), kurtosis(rt))
hyou.a[2,] <- c( mean(rt), sd(rt), 0, 3)
hyou.a[3,] <- c(out.mom$m1, sqrt(out.mom$v2), out.mom$b1, out.mom$b2)
dimnames(hyou.a) <- list( c("sample","N","FSA"), c("E(X)", "sqrt Var(X)", "beta1", "beta2"))
print(xtable(hyou.a, digits=3))
hyou.a
```


# sinh-arcsinh分布からの<br>　乱数生成<br>　(重点サンプリング)

```{r sinh-arcsin_r}
rand.fa<-rfa_SIR_para(n=10000, mu=fit$par2[1],
                                  sigma = fit$par2[2],
                                  lambda = fit$par2[3],
                                  delta = fit$par2[4])

ggplot()+geom_histogram(data=data.frame(sample=rand.fa$q),aes(x=sample),
                        binwidth = 14/100)+theme_bw()+
  theme(axis.title.x = element_text(size=25),axis.title.y = element_text(size=25))+
  theme(axis.text.x = element_text(size=25),axis.text.y = element_text(size=25)) +
  theme(legend.title = element_text(size=25),legend.text = element_text(size=25))
```

## 実際の分布との<br>比較

```{r sinh-arcsin_r2}
df <-data.frame(x=rand.fa$q)
f2 <- ggplot(df,aes(x=x))+
        geom_histogram(aes(y=..density.., fill=..count..),
          binwidth = .15, colour="black") +xlab("log return")+
         scale_fill_gradient("Count", low="#DCDCDC", high="#7C7C7C")+
        theme_bw()+
        theme(#panel.grid.major = element_blank(),
        #panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "black"),
        legend.title=element_blank(),legend.position="none")+
        stat_function(fun=dfas2,
                         #colour="violetred",
                         aes(colour ="red"),
                         size=1,
                         n=401,
                         args=list(mu=fit$par2[1],
                                  sigma = fit$par2[2],
                                  lambda = fit$par2[3],
                                  delta = fit$par2[4]))+
  theme(axis.title.x = element_text(size=25),axis.title.y = element_text(size=25))+
  theme(axis.text.x = element_text(size=25),axis.text.y = element_text(size=25)) +
  theme(legend.title = element_text(size=25),legend.text = element_text(size=25))

f2 
```



# FA分布の<br>　VaRとESの計算

## 分位点を計算する関数

```{r pfa2}
# 確率分布関数のプロット
dx <-seq(-6,6, by=0.01)
pval <- sapply(dx, pfa2, mu=fit$par2[1], sigma=fit$par2[2], lambda=fit$par2[3], delta = fit$par2[4]) 
plot(dx,pval, type="l")

#0が累積確率何%点か確認する
pfa2(0, mu=fit$par2[1], sigma=fit$par2[2], lambda=fit$par2[3], delta = fit$par2[4])

#97.5%点のx(対数収益率)を求める
qfas(0.025, mu=fit$par2[1], sigma=fit$par2[2], lambda=fit$par2[3], delta = fit$par2[4])

# 分位点関数のプロット
px <- seq(0.01, 0.99, by=0.005)
qval <- sapply(px, qfas, mu=fit$par2[1], sigma=fit$par2[2], lambda=fit$par2[3], delta = fit$par2[4]) 
plot(px,qval, type="l")
```

$\alpha=0.01, 0.025, 0.05$にしてVaRとESを推定する. 

## 真値を計算

```{r vares2}
#99%,97.5%,95%の各点に対して，先ほどの関数を用いて求める
VaR1.fa <- qfas(0.01, mu=fit$par2[1], sigma=fit$par2[2],
                lambda=fit$par2[3], delta = fit$par2[4])
VaR25.fa <- qfas(0.025, mu=fit$par2[1], sigma=fit$par2[2],
                 lambda=fit$par2[3], delta = fit$par2[4])
VaR5.fa <- qfas(0.05, mu=fit$par2[1], sigma=fit$par2[2],
                lambda=fit$par2[3], delta = fit$par2[4])
#まとめておく
VaR.true.FA <- c(VaR1.fa ,VaR25.fa ,VaR5.fa )

ES1.fa <- find.ES(p=0.01, par=fit$par2)
ES25.fa <- find.ES(p=0.025, par=fit$par2)
ES5.fa <- find.ES(p=0.05, par=fit$par2)
#まとめる
ES.true.FA <- c(ES1.fa ,ES25.fa ,ES5.fa )
ES.true.FA
```
## 単純<br>モンテカルロ法

```{r SMCforFAdistribution}
SMC.fa.out <- SMC.fa(fit$par2)
```


## IS(重点サンプリング)による<br>VaRとESを計算

```{r IS_FA}
# 99%,97.5%,95%それぞれのVaRと平均が一致するthetaを取得
theta.val1<- find.theta(0.01, fit$par2)
theta.val25<- find.theta(0.025, fit$par2)
theta.val5<- find.theta(0.05, fit$par2)

#97.5%点に関して一致することを確認
qfas(p=0.025, mu=fit$par2[1], sigma=fit$par2[2],
     lambda=fit$par2[3], delta=fit$par2[4])
mean.IS(theta.val25,par=fit$par2)

# 密度関数の確認
dx <- seq(-30,10,length=200)
out1 <- sapply(dx, d.IS, theta=theta.val1, par=fit$par2)
out25 <- sapply(dx, d.IS, theta=theta.val25, par=fit$par2)
out5 <- sapply(dx, d.IS, theta=theta.val5, par=fit$par2)
out <- cbind(out1,out25,out5)
#matplot(dx,out,type="l",lwd=2)
ggplot(data.frame(dx,out) %>% melt('dx'),
       aes(x=dx,y=value,colour=variable))+
  geom_line(size=2)+theme_bw()+
  theme(legend.position = "bottom")+
  theme(axis.title.x = element_text(size=25),axis.title.y = element_text(size=25))+
  theme(axis.text.x = element_text(size=25),axis.text.y = element_text(size=25)) +
  theme(legend.title = element_text(size=25),legend.text = element_text(size=25))


rfa.IS.1<-rIS_SIR(n=20000, par=fit$par2, par2=VaR.true.FA[1], theta=theta.val1)
#hist(rfa.IS.1$q, breaks=100)
ggplot(data.frame(q=rfa.IS.1[[1]]),aes(x=q))+
  geom_histogram()+theme()+theme_bw()+
  theme(axis.title.x = element_text(size=25),axis.title.y = element_text(size=25))+
  theme(axis.text.x = element_text(size=25),axis.text.y = element_text(size=25)) +
  theme(legend.title = element_text(size=25),legend.text = element_text(size=25))


rfa.IS.25<-rIS_SIR(n=20000, par=fit$par2, par2=VaR.true.FA[2], theta=theta.val25)
#hist(rfa.IS.25$q, breaks=100)
ggplot(data.frame(q=rfa.IS.25[[1]]),aes(x=q))+
  geom_histogram()+theme()+theme_bw()+
  theme(axis.title.x = element_text(size=25),axis.title.y = element_text(size=25))+
  theme(axis.text.x = element_text(size=25),axis.text.y = element_text(size=25)) +
  theme(legend.title = element_text(size=25),legend.text = element_text(size=25))


rfa.IS.5<-rIS_SIR(n=20000, par=fit$par2, par2=VaR.true.FA[3], theta=theta.val5)
#hist(rfa.IS.5$q, breaks=100)
ggplot(data.frame(q=rfa.IS.5[[1]]),aes(x=q))+
  geom_histogram()+theme()+theme_bw()+
  theme(axis.title.x = element_text(size=25),axis.title.y = element_text(size=25))+
  theme(axis.text.x = element_text(size=25),axis.text.y = element_text(size=25)) +
  theme(legend.title = element_text(size=25),legend.text = element_text(size=25))


# サンプリングしたものを入力としてFA分布の重点サンプリングを行う
rfa1 <- sample(rfa.IS.1$q, 10000)
rfa25 <- sample(rfa.IS.25$q, 10000)
rfa5 <- sample(rfa.IS.5$q, 10000)

out.fa <- IS.fa(7)
```


## FA分布の<br>ES,VARのSMC,ISの図<br>(収束の様子)

```{r figVaRggplot}
out <-data.frame(100:10000, -out.fa[[1]][,c(1,3,5)],-SMC.fa.out[[1]][,1:3])
names(out)<- c("N", "VaR99(IS)","VaR97.5(IS)","VaR95(IS)",
               "VaR99(SMC)","VaR97.5(SMC)","VaR95(SMC)")

df2=melt(out,id.vars=c("N"))

plot_b=ggplot(df2,aes(N,value,lty=variable,col=variable))+
  geom_line(size=.8)+geom_hline(aes(yintercept=-VaR.true.FA[1]))+
  geom_hline(aes(yintercept=-VaR.true.FA[2]))+
  geom_hline(aes(yintercept=-VaR.true.FA[3]))+
  theme_bw()+ylab("VaR")+
  theme(#panel.grid.major = element_blank(),
        #panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "black"),
        legend.title=element_blank(),legend.position="bottom")+
        theme(legend.key.width=unit(2.5,"cm"))+
  theme(strip.text.x=element_text(size=16))+
  theme(axis.title.x = element_text(size=25),axis.title.y = element_text(size=25))+
  theme(axis.text.x = element_text(size=25),axis.text.y = element_text(size=25)) +
  theme(legend.title = element_text(size=25),legend.text = element_text(size=25))
       
plot_b 
```

```{r figESggplot}
out <-data.frame(100:10000, -out.fa[[1]][,c(2,4,6)],-SMC.fa.out[[1]][,4:6])
names(out)<- c("N","ES99(IS)","ES97.5(IS)","ES95(IS)",
               "ES99(SMC)","ES97.5(SMC)","ES95(SMC)")

df2=melt(out,id.vars=c("N"))

plot_b=ggplot(df2,aes(N,value,lty=variable,col=variable))+
  geom_line(size=.8)+geom_hline(aes(yintercept=-ES.true.FA[1]))+
  geom_hline(aes(yintercept=-ES.true.FA[2]))+
  geom_hline(aes(yintercept=-ES.true.FA[3]))+
  theme_bw()+ylab("ES")+
        theme(#panel.grid.major = element_blank(),
        #panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "black"),
        legend.title=element_blank(),legend.position="bottom")+
        theme(legend.key.width=unit(2.5,"cm"))+
  theme(strip.text.x=element_text(size=16))+
  theme(axis.title.x = element_text(size=25),axis.title.y = element_text(size=25))+
  theme(axis.text.x = element_text(size=25),axis.text.y = element_text(size=25)) +
  theme(legend.title = element_text(size=25),legend.text = element_text(size=25))
plot_b
```





# 正規分布の<br>　VaRとESの推定

## 正規分布の場合:<br>(真値を計算)

```{r norm_answer}
# 正規分布の場合はパラメータは平均と分散だけ
theta <- c(mean(rt), sd(rt))
f <-　function(x)  x*dnorm(x,mean=theta[1], sd=theta[2]) 
VaR.true.norm <- qnorm(c(0.01,0.025,0.05), mean=theta[1], sd=theta[2])
ES.true.norm <- sapply( c(0.01,0.025, 0.05), function(x){
  integrate(f,
            lower=-Inf, upper=qnorm(x,mean=theta[1], sd=theta[2]))$value/x})
```

## 正規分布の場合：<br>(単純モンテカルロ法)

```{r varnormal}
SMC.norm.out <- SMC.norm(theta)
```

## 正規分布の場合：<br>重点サンプリング

```{r Var_normal_IS}
N <-10000
VaR.true <- qnorm(c(0.01,0.025,0.05), mean=theta[1], sd=theta[2])

theta <- c(mean(rt), sd(rt))

## IS for VaR
Expected.val.th <- function(VaR, mu, sd){
    #M <- exp(mu*th+ sd^2*th^2/2)
    #m <- mu+sd^2*th
    return( (VaR - mu)/sd^2 )}

th1 <- Expected.val.th(VaR=VaR.true[1], mu=theta[1], sd = theta[2])

dIS.norm <- function(x, mean, sd, th ) {
  M <- exp(mean*th+ sd^2*th^2/2)  
  dnorm(x, mean=mean, sd =sd) * exp(th*x)/M}

## 結局正規分布の場合は 平均をシフトさせるだけの演算
## dnorm(x , mean = mu+sd^2*th, sd= theta[2] )

##　重点分布からサンプリング
IS1 <- rnorm(10000, mean = theta[1]+theta[2]^2*th1, sd = theta[2])
hist(IS1, breaks=100, prob=TRUE)
dx <- seq(-10,10, length=1000)
lines(dx, sapply(dx, dIS.norm, mean = theta[1], sd = theta[2], th=th1),type="l")
lines(dx, sapply(dx, dnorm, mean = theta[1], sd = theta[2]),col=2)

## ウェイトの計算
M1 <- exp(theta[1]*th1+ theta[2]^2*th1^2/2)  
w1 <- exp(-th1*IS1)*M1

# サンプルと対応するweightをくっつける
out <- cbind( IS1,  w1/N)
A <- out[sort.list(out[,2]),]
A <- cbind(A, cumsum(A[,2]))
# VaR0.01の推定値 
A[which.min(abs(A[,3]-0.01)),]
# ES0.01の推定値
sum(apply(A[1:which.min(abs(A[,3]-0.01)),1:2],1,prod))/0.01 
out.norm <- IS.norm(theta)
```

## 正規分布の<br>ES,VARの図<br>(収束の様子)

```{r, plot1}
## normal VaR
out <-data.frame(c(100:10000),-out.norm[[1]][,c(1,3,5)],-SMC.norm.out[[1]][,1:3])
names(out)<- c("N","VaR0.01(IS)","VaR0.025(IS)","VaR0.05(IS)",
               "VaR0.01(SMC)","VaR0.025(SMC)","VaR0.05(SMC)")

df2=melt(out,id.vars=c("N"))

plot_b=ggplot(df2,aes(N,value,lty=variable,col=variable))+
  geom_line(size=.8)+geom_hline(aes(yintercept=-VaR.true.norm[1]))+
  geom_hline(aes(yintercept=-VaR.true.norm[2]))+
  geom_hline(aes(yintercept=-VaR.true.norm[3]))+
  theme_bw()+ylab("VaR")+
        theme(#panel.grid.major = element_blank(),
        #panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "black"),
        legend.title=element_blank(),legend.position="bottom")+
        theme(legend.key.width=unit(2.5,"cm"))+
  theme(strip.text.x=element_text(size=16))+
  theme(axis.title.x = element_text(size=25),axis.title.y = element_text(size=25))+
  theme(axis.text.x = element_text(size=25),axis.text.y = element_text(size=25)) +
  theme(legend.title = element_text(size=25),legend.text = element_text(size=25))
plot_b


## normal ES
out2 <-data.frame(c(100:10000),-out.norm[[1]][,c(2,4,6)],-SMC.norm.out[[1]][,4:6])
names(out2)<- c("N","ES0.01(IS)","ES0.025(IS)","ES0.05(IS)",
               "ES0.01(SMC)","ES0.025(SMC)","ES0.05(SMC)")

df2=melt(out2,id.vars=c("N"))

plot_b=ggplot(df2,aes(N,value,lty=variable,col=variable))+
  geom_line(size=.8)+geom_hline(aes(yintercept=-ES.true.norm[1]))+
  geom_hline(aes(yintercept=-ES.true.norm[2]))+
  geom_hline(aes(yintercept=-ES.true.norm[3]))+
  theme_bw()+ylab("ES")+
        theme(#panel.grid.major = element_blank(),
        #panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "black"),
        legend.title=element_blank(),legend.position="bottom")+
        theme(legend.key.width=unit(2.5,"cm"))+
  theme(strip.text.x=element_text(size=16))+
  theme(axis.title.x = element_text(size=25),axis.title.y = element_text(size=25))+
  theme(axis.text.x = element_text(size=25),axis.text.y = element_text(size=25)) +
  theme(legend.title = element_text(size=25),legend.text = element_text(size=25))
plot_b
```

## 結果のまとめ

```{r result.table}
hyou1 <- matrix(0,6,6)
hyou1[1,] <- c( VaR.true.norm, ES.true.norm)
hyou1[2,] <- out.norm[[1]][9901,][c(1,3,5,2,4,6)]
hyou1[3,] <-SMC.norm.out[[1]][9901,]
hyou1[4,] <-c( VaR.true.FA, ES.true.FA)
hyou1[5,] <- out.fa[[1]][9901,][c(1,3,5,2,4,6)]
hyou1[6,] <-SMC.fa.out[[1]][9901,]

dimnames(hyou1) <- list(rep(c("True", "IS","SMC"),2), 
                      c("VaR99","VaR97.5","VaR95",
                       "ES99","ES97.5","ES95"))
#print(xtable(hyou1, digit=3)) TeXでレポートを書く場合はxtableを使う
hyou1
```
